"""Update shift_payments table

Revision ID: 2627ba8ebd57
Revises: 7f38c4b48485
Create Date: 2023-11-24 01:43:01.830705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2627ba8ebd57'
down_revision: Union[str, None] = '7f38c4b48485'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shift_payments', sa.Column('nomenclature_sum', sa.DECIMAL(), nullable=True))
    op.add_column('shift_payments', sa.Column('orderdiscount_type', sa.String(), nullable=True))
    op.add_column('shift_payments', sa.Column('orderdiscount_type_id', sa.UUID(), nullable=True))
    op.add_column('shift_payments', sa.Column('orderincrease_type', sa.String(), nullable=True))
    op.add_column('shift_payments', sa.Column('orderincrease_type_id', sa.UUID(), nullable=True))
    op.add_column('shift_payments', sa.Column('itemsalediscount_name', sa.String(), nullable=True))
    op.add_column('shift_payments', sa.Column('fiscalcheque_num', sa.Integer(), nullable=True))
    op.add_column('shift_payments', sa.Column('discountdish_num', sa.DECIMAL(), nullable=True))
    op.add_column('shift_payments', sa.Column('discount_percent', sa.DECIMAL(), nullable=True))
    op.add_column('shift_payments', sa.Column('discount_sum', sa.DECIMAL(), nullable=True))
    op.add_column('shift_payments', sa.Column('increase_percent', sa.DECIMAL(), nullable=True))
    op.add_column('shift_payments', sa.Column('increase_sum', sa.DECIMAL(), nullable=True))
    op.add_column('shift_payments', sa.Column('full_sum', sa.DECIMAL(), nullable=True))
    op.create_foreign_key(None, 'shift_payments', 'reference_units', ['orderincrease_type_id'], ['id'])
    op.create_foreign_key(None, 'shift_payments', 'reference_units', ['orderdiscount_type_id'], ['id'])
    op.drop_column('shift_payments', 'sum')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shift_payments', sa.Column('sum', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'shift_payments', type_='foreignkey')
    op.drop_constraint(None, 'shift_payments', type_='foreignkey')
    op.drop_column('shift_payments', 'full_sum')
    op.drop_column('shift_payments', 'increase_sum')
    op.drop_column('shift_payments', 'increase_percent')
    op.drop_column('shift_payments', 'discount_sum')
    op.drop_column('shift_payments', 'discount_percent')
    op.drop_column('shift_payments', 'discountdish_num')
    op.drop_column('shift_payments', 'fiscalcheque_num')
    op.drop_column('shift_payments', 'itemsalediscount_name')
    op.drop_column('shift_payments', 'orderincrease_type_id')
    op.drop_column('shift_payments', 'orderincrease_type')
    op.drop_column('shift_payments', 'orderdiscount_type_id')
    op.drop_column('shift_payments', 'orderdiscount_type')
    op.drop_column('shift_payments', 'nomenclature_sum')
    # ### end Alembic commands ###
