"""Changes in tables

Revision ID: 27084dec630b
Revises: 4c0dbc89e7f3
Create Date: 2023-12-12 20:57:10.679618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27084dec630b'
down_revision: Union[str, None] = '4c0dbc89e7f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store_incomings', sa.Column('transaction_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('store_incomings', sa.Column('store_name', sa.String(), nullable=True))
    op.add_column('store_incomings', sa.Column('measureunit', sa.String(), nullable=True))
    op.drop_constraint('store_incomings_store_id_fkey', 'store_incomings', type_='foreignkey')
    op.drop_constraint('store_incomings_measureunit_id_fkey', 'store_incomings', type_='foreignkey')
    op.drop_column('store_incomings', 'actual_amount')
    op.drop_column('store_incomings', 'store_id')
    op.drop_column('store_incomings', 'measureunit_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store_incomings', sa.Column('measureunit_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('store_incomings', sa.Column('store_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('store_incomings', sa.Column('actual_amount', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.create_foreign_key('store_incomings_measureunit_id_fkey', 'store_incomings', 'reference_units', ['measureunit_id'], ['id'])
    op.create_foreign_key('store_incomings_store_id_fkey', 'store_incomings', 'stores', ['store_id'], ['id'])
    op.drop_column('store_incomings', 'measureunit')
    op.drop_column('store_incomings', 'store_name')
    op.drop_column('store_incomings', 'transaction_date')
    # ### end Alembic commands ###
