"""New migrate of shift_payments table

Revision ID: 453ca8919e0a
Revises: 8f7380fd680d
Create Date: 2023-11-26 23:24:22.299478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '453ca8919e0a'
down_revision: Union[str, None] = '8f7380fd680d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shift_payments',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('order_num', sa.BIGINT(), nullable=True),
    sa.Column('payment_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('nomenclature_id', sa.UUID(), nullable=True),
    sa.Column('nomenclature_name', sa.String(), nullable=True),
    sa.Column('shift_id', sa.UUID(), nullable=True),
    sa.Column('shift_num', sa.Integer(), nullable=True),
    sa.Column('cashier_id', sa.UUID(), nullable=True),
    sa.Column('soldwithdish_id', sa.UUID(), nullable=True),
    sa.Column('soldwithitem_id', sa.UUID(), nullable=True),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('ordertype_id', sa.UUID(), nullable=True),
    sa.Column('ordertype', sa.String(), nullable=True),
    sa.Column('paymenttype_id', sa.UUID(), nullable=True),
    sa.Column('paymenttype', sa.String(), nullable=True),
    sa.Column('paymenttype_group', sa.String(), nullable=True),
    sa.Column('measure_unit', sa.String(), nullable=True),
    sa.Column('nomenclature_amount', sa.DECIMAL(), nullable=True),
    sa.Column('nomenclature_sum', sa.DECIMAL(), nullable=True),
    sa.Column('is_delivery', sa.String(), nullable=True),
    sa.Column('guest_num', sa.Integer(), nullable=True),
    sa.Column('guestcard_num', sa.String(), nullable=True),
    sa.Column('guestcard_owner', sa.String(), nullable=True),
    sa.Column('paymentcard_num', sa.String(), nullable=True),
    sa.Column('bonuscard_num', sa.String(), nullable=True),
    sa.Column('orderdiscount_type', sa.String(), nullable=True),
    sa.Column('orderdiscount_type_id', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('orderincrease_type', sa.String(), nullable=True),
    sa.Column('orderincrease_type_id', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('itemsalediscount_name', sa.String(), nullable=True),
    sa.Column('fiscalcheque_num', sa.Integer(), nullable=True),
    sa.Column('discountdish_num', sa.DECIMAL(), nullable=True),
    sa.Column('discount_percent', sa.DECIMAL(), nullable=True),
    sa.Column('discount_sum', sa.DECIMAL(), nullable=True),
    sa.Column('increase_percent', sa.DECIMAL(), nullable=True),
    sa.Column('increase_sum', sa.DECIMAL(), nullable=True),
    sa.Column('full_sum', sa.DECIMAL(), nullable=True),
    sa.Column('last_update', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cashier_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['nomenclature_id'], ['nomenclatures.id'], ),
    sa.ForeignKeyConstraint(['ordertype_id'], ['reference_units.id'], ),
    sa.ForeignKeyConstraint(['paymenttype_id'], ['reference_units.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shift_list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shift_payments')
    # ### end Alembic commands ###
