"""Update Store incomings table

Revision ID: 4c0dbc89e7f3
Revises: 946f83aeee48
Create Date: 2023-12-11 18:36:19.901924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4c0dbc89e7f3'
down_revision: Union[str, None] = '946f83aeee48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store_incomings', sa.Column('counteragent_id', sa.UUID(), nullable=True))
    op.add_column('store_incomings', sa.Column('counteragent_type', sa.String(), nullable=True))
    op.drop_column('store_incomings', 'price')
    op.drop_column('store_incomings', 'price_withoutVat')
    op.drop_column('store_incomings', 'supplier_id')
    op.drop_column('store_incomings', 'incoming_invoice_id')
    op.drop_column('store_incomings', 'due_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store_incomings', sa.Column('due_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('store_incomings', sa.Column('incoming_invoice_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('store_incomings', sa.Column('supplier_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('store_incomings', sa.Column('price_withoutVat', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('store_incomings', sa.Column('price', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.drop_column('store_incomings', 'counteragent_type')
    op.drop_column('store_incomings', 'counteragent_id')
    # ### end Alembic commands ###
